global using FisketorvetInfinte.Models;
global using FisketorvetInfinte.Helpers;
global using System.IO;
global using System.Collections.Generic;
global using System;
global using Newtonsoft.Json;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
